spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/day1103?serverTimezone=UTC
#    ?serverTimezone=UTC
#    jdbc:mysql://localhost:3306/day1029?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
